Repository SzFMV2021-Osz/AutomatedCar-A, pull requests merged in 2021-10, with the labels that each got.

#24 #15 Elemek filterezése
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/Models/IAutomatedCar.cs
  src/AutomatedCar/Models/IWorldObject.cs
  src/AutomatedCar/Models/WorldObject.cs
  src/AutomatedCar/SystemComponents/Sensors/Camera.cs
  test/AutomatedCarTests/AutomatedCarTests.csproj
  test/AutomatedCarTests/Models/CircleTests.cs
  test/AutomatedCarTests/SystemComponents/Sensors/CameraTest.cs
Labels: effort: moderate, priority: high

#13 [Team-A1] #8 Gas and break pedal implementation
  src/AutomatedCar/App.xaml.cs
  src/AutomatedCar/Game.cs
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/Models/Car.cs
  src/AutomatedCar/Models/IAutomatedCar.cs
  src/AutomatedCar/Models/Vector.cs
  src/AutomatedCar/Models/World.cs
  src/AutomatedCar/ViewModels/MainWindowViewModel.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/MainWindow.xaml.cs
  test/AutomatedCarTests/CarControlUnitTest.cs
Labels: effort: moderate, priority: high, status: review needed, type: enhancement

#35 Sensors are communicating with VFB
  src/AutomatedCar/App.xaml.cs
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/SystemComponents/Packets/CameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/CollisionDetectionPacket.cs
  src/AutomatedCar/SystemComponents/Packets/ICameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IRadarPacket.cs
  src/AutomatedCar/SystemComponents/Packets/ISensorPacket.cs
  src/AutomatedCar/SystemComponents/Packets/RadarPacket.cs
  src/AutomatedCar/SystemComponents/Packets/SensorPacket.cs
  src/AutomatedCar/SystemComponents/Sensors/Camera.cs
  src/AutomatedCar/SystemComponents/Sensors/ISensor.cs
  src/AutomatedCar/SystemComponents/Sensors/Radar.cs
  src/AutomatedCar/SystemComponents/Sensors/Sensor.cs
  src/AutomatedCar/SystemComponents/VirtualFunctionBus.cs
  test/AutomatedCarTests/SystemComponents/Sensors/CameraTest.cs
Labels: effort: high, priority: critical, status: review needed, type: enhancement

#45 Sensors are now collecting sensor specific data.
  src/AutomatedCar/SystemComponents/Packets/CameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/ICameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IRadarPacket.cs
  src/AutomatedCar/SystemComponents/Packets/ISensorPacket.cs
  src/AutomatedCar/SystemComponents/Packets/RadarPacket.cs
  src/AutomatedCar/SystemComponents/Sensors/Camera.cs
  src/AutomatedCar/SystemComponents/Sensors/Radar.cs
  src/AutomatedCar/SystemComponents/Sensors/Sensor.cs
Labels: effort: moderate, status: review needed, type: enhancement
