Repository SzFMV2021-Osz/AutomatedCar-A, pull requests merged in 2021-11, with the labels that each got.

#77 [Team-A2] #43 & #42 Lane keeping assistance and feedback
  src/AutomatedCar/App.xaml.cs
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/Models/LaneKeepingModel.cs
  src/AutomatedCar/SystemComponents/Helpers/LaneKeeping.cs
  src/AutomatedCar/SystemComponents/Helpers/LaneKeepingStatus.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/CameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/CollisionDetectionPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/LaneKeepingPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/RadarPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/SensorPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ICameraPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ICollisionDetectionPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ILaneKeepingPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/IRadarPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ISensorPacket.cs
  src/AutomatedCar/SystemComponents/VirtualFunctionBus.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/MainWindow.xaml.cs
Labels: type: enhancement

#76 [Team-A1] 69 - Car speed downscale
  src/AutomatedCar/Models/AutomatedCar.cs
Labels: effort: low, priority: normal, status: review needed, type: enhancement

#84 Major refactor for Lane Keeping Assistant
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/Models/LKAModel.cs
  src/AutomatedCar/Models/WorldObject.cs
  src/AutomatedCar/SystemComponents/Helpers/CollisionDetection.cs
  src/AutomatedCar/SystemComponents/Helpers/CollisionType.cs
  src/AutomatedCar/SystemComponents/Helpers/LaneKeeping.cs
  src/AutomatedCar/SystemComponents/Helpers/LaneKeepingAssistant.cs
  src/AutomatedCar/SystemComponents/Helpers/LaneKeepingStatus.cs
  src/AutomatedCar/SystemComponents/Helpers/Utils.cs
  src/AutomatedCar/SystemComponents/Packets/Classes/LKAPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ICollisionDetectionPacket.cs
  src/AutomatedCar/SystemComponents/Packets/Interfaces/ILKAPacket.cs
  src/AutomatedCar/SystemComponents/Sensors/Radar.cs
  src/AutomatedCar/SystemComponents/Sensors/Sensor.cs
  src/AutomatedCar/SystemComponents/VirtualFunctionBus.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/MainWindow.xaml.cs
  test/AutomatedCarTests/CarCollisionUnitTest.cs
Labels: effort: moderate, priority: high, status: review needed, type: enhancement

#87 Lane keeping improvement
  src/AutomatedCar/SystemComponents/Helpers/LaneKeepingAssistant.cs
Labels: effort: low, priority: normal, status: completed, type: enhancement
